### ISSUE TITLE
[suggestion] specify engines in package.json

### ISSUE THREAD

**Issue by Nykho** [input-output-hk/rust-cardano-crypto#18]
Hi. I would suggest to specify node and npm/ yarn version in the `package.json`. https://docs.npmjs.com/files/package.json#engines

**Comment by vincenthz** [comment]
@DominikGuzei any suggestion here ?

**Comment by DominikGuzei** [comment]
@vincenthz you can use the same as we do in Daedalus: https://github.com/input-output-hk/daedalus/blob/develop/package.json#L154
